CREATE TABLE `Voters` (
  `CountyCode` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `RegistrationNbr` varchar(8) COLLATE utf8_unicode_ci NOT NULL,
  `VoterStatus` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VoterLastName` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VoterFirstName` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VoterMiddleMaiden` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VoterNameSuffix` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VoterNameTitle` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResHouseNbr` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResStreetName` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResStreetSuffix` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResAptUnitNbr` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResCityName` varchar(17) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResZip` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResZipPlus4` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MidrFlag` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PollWorker` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TransactionCode` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TransactionYearMonth` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Filler1` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DateOfBirth` date DEFAULT NULL,
  `RegistrationDate` date DEFAULT NULL,
  `Race` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Gender` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Absentee` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LandDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LandLot` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `OriginalRegDate` date DEFAULT NULL,
  `StatusReason` varchar(9) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Filler2` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CountyPrecinctId` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityPrecinctId` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CongressionalDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SenateDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `HouseDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `JudicialDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CommDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SchoolDistrict` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CountyDistAName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CountyDistAValue` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CountyDistBName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CountyDistBValue` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MunicipalName` varchar(17) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MunicipalCode` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `WardCityCouncilName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `WardCityCouncil` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CitySchoolDistName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CitySchoolDist` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistAName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistAValue` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistBName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistBValue` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistCName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistCValue` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistDName` varchar(13) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CityDistDValue` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DateLastVotedDate` date DEFAULT NULL,
  `TypeOfElection` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PartyLastVoted` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LastContactDate` date DEFAULT NULL,
  `MailHouseNbr` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailStreetName` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailStreetSuffix` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailAptUnitNbr` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailCity` varchar(17) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailState` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailZip` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailZipPlus4` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Filler3` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailAddress2` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailAddress3` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailCounty` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DateAdded` date DEFAULT NULL,
  `DateChanged` date DEFAULT NULL,
  `DistrictCombo` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ResBuilding` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MailRRPOBox` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CombinedStreetAddr` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ExportDate` date NOT NULL,
  PRIMARY KEY (`CountyCode`,`RegistrationNbr`,`ExportDate`),
  KEY `CountyCode` (`CountyCode`),
  KEY `RegistrationNbr` (`RegistrationNbr`),
  KEY `VoterStatus` (`VoterStatus`),
  KEY `VoterLastName` (`VoterLastName`),
  KEY `VoterFirstName` (`VoterFirstName`),
  KEY `VoterMiddleMaiden` (`VoterMiddleMaiden`),
  KEY `VoterNameSuffix` (`VoterNameSuffix`),
  KEY `VoterNameTitle` (`VoterNameTitle`),
  KEY `ExportDate` (`ExportDate`),
  KEY `ResHouseNbr` (`ResHouseNbr`),
  KEY `ResStreetName` (`ResStreetName`),
  KEY `ResStreetSuffix` (`ResStreetSuffix`),
  KEY `ResAptUnitNbr` (`ResAptUnitNbr`),
  KEY `ResCityName` (`ResCityName`),
  KEY `ResZip` (`ResZip`),
  KEY `ResZipPlus4` (`ResZipPlus4`),
  KEY `DateOfBirth` (`DateOfBirth`),
  KEY `Race` (`Race`),
  KEY `Gender` (`Gender`),
  KEY `Absentee` (`Absentee`),
  KEY `CountyPrecinctId` (`CountyPrecinctId`),
  KEY `CityPrecinctId` (`CityPrecinctId`),
  KEY `CongressionalDistrict` (`CongressionalDistrict`),
  KEY `SenateDistrict` (`SenateDistrict`),
  KEY `HouseDistrict` (`HouseDistrict`),
  KEY `JudicialDistrict` (`JudicialDistrict`),
  KEY `CommDistrict` (`CommDistrict`),
  KEY `SchoolDistrict` (`SchoolDistrict`),
  KEY `CountyDistAName` (`CountyDistAName`),
  KEY `CountyDistAValue` (`CountyDistAValue`),
  KEY `CountyDistBName` (`CountyDistBName`),
  KEY `CountyDistBValue` (`CountyDistBValue`),
  KEY `MunicipalName` (`MunicipalName`),
  KEY `MunicipalCode` (`MunicipalCode`),
  KEY `WardCityCouncilName` (`WardCityCouncilName`),
  KEY `WardCityCouncil` (`WardCityCouncil`),
  KEY `CitySchoolDistName` (`CitySchoolDistName`),
  KEY `CitySchoolDist` (`CitySchoolDist`),
  KEY `CityDistAName` (`CityDistAName`),
  KEY `CityDistAValue` (`CityDistAValue`),
  KEY `CityDistBName` (`CityDistBName`),
  KEY `CityDistBValue` (`CityDistBValue`),
  KEY `CityDistCName` (`CityDistCName`),
  KEY `CityDistCValue` (`CityDistCValue`),
  KEY `CityDistDName` (`CityDistDName`),
  KEY `CityDistDValue` (`CityDistDValue`),
  KEY `DateLastVotedDate` (`DateLastVotedDate`),
  KEY `TypeOfElection` (`TypeOfElection`),
  KEY `PartyLastVoted` (`PartyLastVoted`),
  KEY `MailHouseNbr` (`MailHouseNbr`),
  KEY `MailStreetName` (`MailStreetName`),
  KEY `MailStreetSuffix` (`MailStreetSuffix`),
  KEY `MailAptUnitNbr` (`MailAptUnitNbr`),
  KEY `MailCity` (`MailCity`),
  KEY `MailState` (`MailState`),
  KEY `MailZip` (`MailZip`),
  KEY `MailZipPlus4` (`MailZipPlus4`),
  KEY `MailAddress2` (`MailAddress2`),
  KEY `MailAddress3` (`MailAddress3`),
  KEY `MailCounty` (`MailCounty`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;





