#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('America/Los_Angeles'); 

/* Use 128M memory it may need */
ini_set('memory_limit', '128M');

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php'; 

// import the Symfony Console Application 
use Symfony\Component\Console\Application; 
use GCG\votertools\GeorgiaCreateSchemaCommand;
use GCG\votertools\FloridaCreateSchemaCommand;

$app = new Application();
$app->add(new GeorgiaCreateSchemaCommand());
$app->add(new FloridaCreateSchemaCommand());
$app->run();
?>