INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('','','');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('AIP','American\'s Party of Florida ','Americans');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('CPF','Constitution Party of Florida ','Constitutions');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('DEM','Florida Democratic Party','Democrats');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('ECO','Ecology Party of Florida ','Ecologies');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('FPP','Florida Pirate Party','Pirates');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('FWP','Florida Whig Party ','Whigs');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('GRE','Green Party of Florida','Greens');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('IDP','Independence Party of Florida ','Independences');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('INT','Independent Party of Florida ','Independents');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('LIB','Libertarian Party of Florida','Libertarians');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('LPF','Libertarian Party of Florida','Libertarians');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('OBJ','Objectivist Party of Florida','Objectivists');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('PSL','Party for Socialism and Liberation-Florida','Socialists');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('REF','Reform Party ','Reforms');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('REP','Republican Party of Florida','Republicans');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('TPF','Tea Party of Florida','Teas');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('PFP','Peace & Freedom Party of Florida','Peaces');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('FSW','Florida Socialist Workers Party','Socialist Workers');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('JPF','Justice Party of Florida','Justices');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('NPA','No Party Affiliation','Nones');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('NRS','No Registration Status','Nones');
INSERT IGNORE INTO `Parties` (`Code`,`Name`,`ShortName`) VALUES ('UNK','Unknown','Nones');
