---
- name: Install composer dependencies
  dnf:
    name: "{{ item }}"
    state: present
  when: inventory_hostname == "fedora"
  with_items:
      - curl
      - libcurl
      - php
      
- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args: 
    creates: /usr/local/bin/composer
    
- name: Setup oauth key for composer
  composer:
    command: config
    working_dir: "{{ composer_working_directory }}"
    arguments: "--global github-oauth.github.com {{ composer_github_oauth }}"
  become: yes
  become_user: "{{ composer_user }}}"