---
- name: create bin and etc folders in home folder
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/bin
    - ~/etc/votertools
- name: Copy PHAR to remote host
  copy:
    src: "../bin/votertools.phar"
    dest: ~/bin/votertools
- file:
    path: ~/bin/votertools
    mode: 0755
- name: create votertools config
  template:
    src="../templates/votertools.yml.j2"
    dest="~/etc/votertools/votertools.yml"
    mode=0644
    backup=no

