---
- name: Add gem fpm
  include: gems_fpm.yml
- name: Add composer
  include: composer.yml
- name: Update composer dependencies
  composer:
    command: "{{ item }}"
    working_dir: "../"
  with_items:
    - install
    - update
- name: Build the package
  shell: "{{ item }}"
  args:
    chdir: "../"
  with_items:
    - "npm cache clean"
    - "npm prune"
    - "npm install --ignore-scripts"
    - "rm -rf bin"
    - "mkdir -p bin"
    - "vendor/bin/box build"
- name: Build the RPM package
  shell: "{{ item }}"
  args:
    chdir: "../"
  with_items:
    - 'rm -rf deploy'
    - "mkdir -p deploy"
    - "node_modules/grunt-cli/bin/grunt shell:fpmrpm"
    - "node_modules/grunt-cli/bin/grunt shell:fpmdeb"
