---
- name: Install node.js packages
  dnf: 
    name: "{{ item }}" 
    state: present
  with_items:
      - nodejs
      - nodejs-devel
      - npm
  when: inventory_hostname == "fedora"
- name: Setup Nodejs
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  when: inventory_hostname == "debian"
- name: Installing Nodejs packages!
  apt: 
    name: "{{item}}" 
    state: installed
  with_items:
    - nodejs 
    - build-essential
  when: inventory_hostname == "debian"
