---
- hosts: "{{ target_hosts }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
#  roles:
#    - votertools
  vars:
    package_settings: "{{ skip_var | default(lookup('file','../package.json') | from_json) }}"
  tasks:
    - name: Execute the build
      include_tasks: build.yml
      tags:
        - build
    - name: Execute the deploy
      include_tasks: deploy.yml
      tags:
        - deploy
    - name: Execute the data
      include_tasks: data.yml
      tags:
        - data
